Repository devblogs-ir/MicroWebFramework, pull requests merged in 2024-01, with the labels that each got.

#25 sets up an http listener and listens for incoming http requests.
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework.sln
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/Builders/PipelineBuilder.cs
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/Controllers/ProductController.cs
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/Controllers/UserController.cs
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/Exceptions/IPNullException.cs
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/Exceptions/InvalidIPException.cs
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/Framework.cs
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/MicroWebFramework.csproj
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/Models/HttpContext.cs
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/Models/Product.cs
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/Models/User.cs
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/Pipes/AuthenticationPipe.cs
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/Pipes/EndPointPipe.cs
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/Pipes/ExceptionHandlingPipe.cs
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/Pipes/Pipe.cs
  sources/Nazanin-Abbasi/MicroWebFramework/MicroWebFramework/Program.cs
Labels: ** ready to review **

#7 Feat/zahra liaghatmand
  sources/ZahraLiaghatmand/Controllers/BaseController.cs
  sources/ZahraLiaghatmand/Controllers/HomeController.cs
  sources/ZahraLiaghatmand/Controllers/NonController.cs
  sources/ZahraLiaghatmand/Controllers/OrdersController.cs
  sources/ZahraLiaghatmand/Controllers/ProductsController.cs
  sources/ZahraLiaghatmand/Exceptions/IPBanException.cs
  sources/ZahraLiaghatmand/Framework.cs
  sources/ZahraLiaghatmand/HttpContext.cs
  sources/ZahraLiaghatmand/PipelineDesignPattern.csproj
  sources/ZahraLiaghatmand/PipelineDesignPattern.sln
  sources/ZahraLiaghatmand/Pipes/AuthenticationPipe.cs
  sources/ZahraLiaghatmand/Pipes/EndpointPipe.cs
  sources/ZahraLiaghatmand/Pipes/ExceptionHandlingPipe.cs
  sources/ZahraLiaghatmand/Pipes/Pipe.cs
  sources/ZahraLiaghatmand/Program.cs
Labels: ** ready to review **

#8 Feat/hamidreza rahmani
  sources/hamidreza-rahmani/MicroWebFramework/Controller/OrderController.cs
  sources/hamidreza-rahmani/MicroWebFramework/Controller/ProductsController.cs
  sources/hamidreza-rahmani/MicroWebFramework/Exception/BadRequestExeption.cs
  sources/hamidreza-rahmani/MicroWebFramework/Exception/BlockedIpExeption.cs
  sources/hamidreza-rahmani/MicroWebFramework/HttpContext.cs
  sources/hamidreza-rahmani/MicroWebFramework/MicroWebFramework.csproj
  sources/hamidreza-rahmani/MicroWebFramework/Middleware/AuthenticationHandler.cs
  sources/hamidreza-rahmani/MicroWebFramework/Middleware/CorsHandler.cs
  sources/hamidreza-rahmani/MicroWebFramework/Middleware/EndpointHandler.cs
  sources/hamidreza-rahmani/MicroWebFramework/Model/Order.cs
  sources/hamidreza-rahmani/MicroWebFramework/Model/Product.cs
  sources/hamidreza-rahmani/MicroWebFramework/ObjectPool.cs
  sources/hamidreza-rahmani/MicroWebFramework/Program.cs
  sources/hamidreza-rahmani/MicroWebFramework/pipeline/Pipeline.cs
  sources/hamidreza-rahmani/MicroWebFramework/pipeline/PiplineBuilder.cs
Labels: ** ready to review **

#20 Feat/sara gholampour
  MicroWebFramework.sln
  sources/SaraGholampour/MicroWebFrameWork/HttpContext.cs
  sources/SaraGholampour/MicroWebFrameWork/InvalidException.cs
  sources/SaraGholampour/MicroWebFrameWork/MicroWebFrameWork.csproj
  sources/SaraGholampour/MicroWebFrameWork/MicroWebFrameWork.sln
  sources/SaraGholampour/MicroWebFrameWork/NotProvidedIpException.cs
  sources/SaraGholampour/MicroWebFrameWork/PipeLineBuilder.cs
  sources/SaraGholampour/MicroWebFrameWork/Pipes.cs
  sources/SaraGholampour/MicroWebFrameWork/ProductController.cs
  sources/SaraGholampour/MicroWebFrameWork/Program.cs
  sources/SaraGholampour/MicroWebFrameWork/ReadUrl.cs
Labels: ** ready to review **

#22 feat: adding support for httplistener and get methods with query string
  sources/Javid Hassani/MicroFramwork/MicroFramwork.sln
  sources/Javid Hassani/MicroFramwork/MicroFramwork/ApplicationContext.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Common/ApplicationBase.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Common/AssemblyExtension.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Common/RequestExtension.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Common/ResponseExtension.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Controllers/BaseController.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Controllers/UserController.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Exceptions/ForbiddenAccessException.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Exceptions/InvalidBindingException.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Exceptions/NotFoundException.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Exceptions/TypeNotFoundException.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/MicroFramwork.csproj
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Model/User.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/PipelineBuilder.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Pipes/AuthorizationMiddleware.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Pipes/ExceptionHandlerMiddleware.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Pipes/Middleware.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Pipes/RequestMappingMiddleware.cs
  sources/Javid Hassani/MicroFramwork/MicroFramwork/Program.cs
Labels: need some changes

#24 CreateBase
  sources/ArashKazemzadeh/MicroWebFramework/Authentication.cs
  sources/ArashKazemzadeh/MicroWebFramework/EndPoint.cs
  sources/ArashKazemzadeh/MicroWebFramework/ExceptionHandling.cs
  sources/ArashKazemzadeh/MicroWebFramework/HttpContext.cs
  sources/ArashKazemzadeh/MicroWebFramework/MicroWebFramework.csproj
  sources/ArashKazemzadeh/MicroWebFramework/MicroWebFramework.sln
  sources/ArashKazemzadeh/MicroWebFramework/Pipe.cs
  sources/ArashKazemzadeh/MicroWebFramework/PipeLineBuilder.cs
  sources/ArashKazemzadeh/MicroWebFramework/ProductsController.cs
  sources/ArashKazemzadeh/MicroWebFramework/Program.cs
Labels: need some changes

#13 'feat/AhadHosseini'
  sources/AhadHosseini/MicroWebFramework.sln
  sources/AhadHosseini/MicroWebFramework/Controllers/Controller.cs
  sources/AhadHosseini/MicroWebFramework/Controllers/OrdersController.cs
  sources/AhadHosseini/MicroWebFramework/Controllers/ProductsController.cs
  sources/AhadHosseini/MicroWebFramework/Framework.cs
  sources/AhadHosseini/MicroWebFramework/MicroWebFramework.csproj
  sources/AhadHosseini/MicroWebFramework/Models/HttpContext.cs
  sources/AhadHosseini/MicroWebFramework/Models/Order.cs
  sources/AhadHosseini/MicroWebFramework/Models/Product.cs
  sources/AhadHosseini/MicroWebFramework/Pipe/AuthenticationPipe.cs
  sources/AhadHosseini/MicroWebFramework/Pipe/EndPointPipe.cs
  sources/AhadHosseini/MicroWebFramework/Pipe/ExceptionHandlingPipe.cs
  sources/AhadHosseini/MicroWebFramework/Pipe/Pipe.cs
  sources/AhadHosseini/MicroWebFramework/Pipe/PipeLineBuilder.cs
  sources/AhadHosseini/MicroWebFramework/Program.cs
Labels: ** ready to review **, need some changes

#16 listens to http and sends the response
  sources/Arezoo Kamane/MicroWebFramework.sln
  sources/Arezoo Kamane/MicroWebFramework/Controllers/ProductsController.cs
  sources/Arezoo Kamane/MicroWebFramework/Controllers/UsersController.cs
  sources/Arezoo Kamane/MicroWebFramework/HttpContext.cs
  sources/Arezoo Kamane/MicroWebFramework/MicroWebFramework.csproj
  sources/Arezoo Kamane/MicroWebFramework/Models/Product.cs
  sources/Arezoo Kamane/MicroWebFramework/Models/User.cs
  sources/Arezoo Kamane/MicroWebFramework/Pipeline/BasePipe.cs
  sources/Arezoo Kamane/MicroWebFramework/Pipeline/PipelineBuilder.cs
  sources/Arezoo Kamane/MicroWebFramework/Pipes/AuthenticationPipe.cs
  sources/Arezoo Kamane/MicroWebFramework/Pipes/EndPointPipe.cs
  sources/Arezoo Kamane/MicroWebFramework/Pipes/ExceptionHandlingPipe.cs
  sources/Arezoo Kamane/MicroWebFramework/Program.cs
Labels: ** ready to review **

#19 Create MicroFramework
  MicroWebFramework.sln
  sources/ArvinMashayekhi/MicroWebFramework/Common/BasePipe.cs
  sources/ArvinMashayekhi/MicroWebFramework/Common/HttpContext.cs
  sources/ArvinMashayekhi/MicroWebFramework/Controllers/SetOrderController.cs
  sources/ArvinMashayekhi/MicroWebFramework/Controllers/UserController.cs
  sources/ArvinMashayekhi/MicroWebFramework/Entities/Order.cs
  sources/ArvinMashayekhi/MicroWebFramework/Entities/User.cs
  sources/ArvinMashayekhi/MicroWebFramework/Exeptions/ExeptionHandler.cs
  sources/ArvinMashayekhi/MicroWebFramework/MicroWebFramework.csproj
  sources/ArvinMashayekhi/MicroWebFramework/Pipelines/AuthenticationPipeline.cs
  sources/ArvinMashayekhi/MicroWebFramework/Pipelines/EndPointPipeline.cs
  sources/ArvinMashayekhi/MicroWebFramework/Pipelines/PipelineBuilder.cs
  sources/ArvinMashayekhi/MicroWebFramework/Program.cs
  sources/ArvinMashayekhi/MicroWebFramework/Services/IUserService.cs
  sources/ArvinMashayekhi/MicroWebFramework/Services/UserService.cs
Labels: ** ready to review **, need some changes

#21 adding request and response
  sources/MohammadZarei/MicroWebFramework/MicroWebFramework.sln
  sources/MohammadZarei/MicroWebFramework/MicroWebFramework/Context.cs
  sources/MohammadZarei/MicroWebFramework/MicroWebFramework/Controllers/UsersController.cs
  sources/MohammadZarei/MicroWebFramework/MicroWebFramework/Exceptions/BlockedIpException.cs
  sources/MohammadZarei/MicroWebFramework/MicroWebFramework/MicroWebFramework.csproj
  sources/MohammadZarei/MicroWebFramework/MicroWebFramework/PipelineBuilder.cs
  sources/MohammadZarei/MicroWebFramework/MicroWebFramework/Pipes/ApplicationConsts.cs
  sources/MohammadZarei/MicroWebFramework/MicroWebFramework/Pipes/AuthenticatingHandler.cs
  sources/MohammadZarei/MicroWebFramework/MicroWebFramework/Pipes/EndpointHandler.cs
  sources/MohammadZarei/MicroWebFramework/MicroWebFramework/Pipes/ExceptionHandler.cs
  sources/MohammadZarei/MicroWebFramework/MicroWebFramework/Pipes/Pipe.cs
  sources/MohammadZarei/MicroWebFramework/MicroWebFramework/Program.cs
  sources/MohammadZarei/MicroWebFramework/MicroWebFramework/User.cs
Labels: ** ready to review **, need some changes

#27 MicroWebFramework #Review 20240101
  sources/ArashKazemzadeh/MicroWebFramework/Controllers/OrdersController.cs
  sources/ArashKazemzadeh/MicroWebFramework/Controllers/ProductsController.cs
  sources/ArashKazemzadeh/MicroWebFramework/HttpContext.cs
  sources/ArashKazemzadeh/MicroWebFramework/Middlewares/Authentication.cs
  sources/ArashKazemzadeh/MicroWebFramework/Middlewares/EndPoint.cs
  sources/ArashKazemzadeh/MicroWebFramework/Middlewares/ExceptionHandling.cs
  sources/ArashKazemzadeh/MicroWebFramework/Models/HttpContext.cs
  sources/ArashKazemzadeh/MicroWebFramework/PipLines/Pipe.cs
  sources/ArashKazemzadeh/MicroWebFramework/PipLines/PipeLineBuilder.cs
  sources/ArashKazemzadeh/MicroWebFramework/Program.cs
  sources/MojtabaValizadeh/MicroWebFramework/Program.cs
Labels: ** ready to review **
